// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PurchaseAPI.Infrastructure.Contexts;

#nullable disable

namespace PurchaseAPI.Migrations
{
    [DbContext(typeof(PurchaseDBContext))]
    partial class PurchaseDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("PurchaseAPI.Models.Purchase", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("purchase_date")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("id"));

                    b.ToTable("Purchases");
                });

            modelBuilder.Entity("PurchaseAPI.Models.PurchaseDetail", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<int>("item_id")
                        .HasColumnType("int");

                    b.Property<int>("purchase_id")
                        .HasColumnType("int");

                    b.Property<float>("qty")
                        .HasColumnType("real");

                    b.Property<float>("rate")
                        .HasColumnType("real");

                    b.HasKey("id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("id"));

                    b.HasIndex("purchase_id");

                    b.ToTable("PurchaseDetails");
                });

            modelBuilder.Entity("PurchaseAPI.Models.PurchaseDetail", b =>
                {
                    b.HasOne("PurchaseAPI.Models.Purchase", "Purchase")
                        .WithMany("PurchaseDetails")
                        .HasForeignKey("purchase_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Purchase");
                });

            modelBuilder.Entity("PurchaseAPI.Models.Purchase", b =>
                {
                    b.Navigation("PurchaseDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
